name: Deploy To QA

on: [workflow_call]

jobs:
  push-to-npm:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v3
      - name: Update package.json file
      - run: |
          plugin_version=$(echo "${{github.ref_name}}" | grep -Eo '[0-9].[0-9].[0-9]+-rc[0-9]+')
          npm version $plugin_version
          git config --global user.name "amit.kremer"
          git config --global user.email "amit.kremer@appsflyer.com"
          git commit -m "QA version published with github-ci"
          git push
      - name: Push to NPM
      - run: |
          npm publish --dry-run


  report-slack:
    runs-on: ubuntu-latest
    environment: Staging
    needs: [push-to-npm]
    steps:
      - run: |
          echo "here we report slack"