name: Deploy To QA

on: [workflow_call]

jobs:
  push-to-npm:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - run: |
          version="US/Central - 10:26 PM (CST)" | grep -oP "\-\s+\K\d{2}:\d{2}"
          echo "${version}"

  report-slack:
    runs-on: ubuntu-latest
    environment: Staging
    needs: [push-to-npm]
    steps:
      - run: |
          echo "here we report slack"