name: Deploy To QA

on: [workflow_call]

jobs:
  Deploy-to-QA:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v3
      - name: Login to Github
        env: 
          COMMIT_AUTHOR: ${{ secrets.CI_COMMIT_AUTHOR }}
          COMMIT_EMAIL: ${{ secrets.CI_COMMIT_EMAIL }}
        run: |
          git config --global user.name env.COMMIT_AUTHOR
          git config --global user.email env.COMMIT_EMAIL

      - name: Update package.json file
        run: |
          plugin_version=$(echo "${{github.ref_name}}" | grep -Eo '[0-9].[0-9].[0-9]+-rc[0-9]+')
          echo "Updating plugin to version $plugin_version"
          npm version $plugin_version
          git push

      - name: Push to NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        uses: JS-DevTools/npm-publish@v1
        with:
          token: env.NPM_TOKEN
          dry-run: true
          tag: QA
      
      - name: Get Jira tickets for version
        run: |
          fixed_version=$(echo "${{github.ref_name}}" | grep -Eo '[0-9].[0-9].[0-9]+')
          jira_fixed_version="React-Native SDK v$fixed_version"
          echo "Getting jira tickets related to $jira_fixed_version"
          curl -X GET -H "Authorization: Basic bWF4aW1AYXBwc2ZseWVyLmNvbTp3Nk1OaGJSYUZsZnNhMXBiOEZkdzU3MDU=" https://appsflyer.atlassian.net/rest/api/3/project/11400/versions | jq -r '.[].name' | while read name ; do
            if [${name} == ${jira_fixed_version}]; then
              echo "${name}"
            fi
          done

      - name: Generate slack report
        run: | 
          echo slack report generated

      - name: Send slack report
        run: |
          echo slack report sent