name: New release workflow

on:
  pull_request:
    types: [opened]

jobs:
    Start-MR-To-Master:
      if: startsWith(github.head_ref, 'releases/')
      uses: ./.github/workflows/mr-opened-to-master.yml
      secrets: inherit