name: New plugin release workflow

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
jobs:
  Deploy-To-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Github
        env:
          COMMIT_AUTHOR: ${{ secrets.CI_COMMIT_AUTHOR }}
          COMMIT_EMAIL: ${{ secrets.CI_COMMIT_EMAIL }}
        run: |
          git config --global user.name env.COMMIT_AUTHOR
          git config --global user.email env.COMMIT_EMAIL
      
      - name: Create new release
        run: |
          echo "push new release"
      
      - name: Push to NPM
        env:
          CI_NPM_TOKEN: ${{ secrets.CI_NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$CI_NPM_TOKEN" > ~/.npmrc
          npm publish --dry-run

      - name: Download a single artifact
        uses : actions/download-artifact@v2
        with:
          name: $(echo "${{github.ref_name}}" | grep -Eo '[0-9].[0-9].[0-9]+') + "-releasenotes"
      - name: Generate and send slack report
        run: |
          VAR=$(echo "${{github.ref_name}}" | grep -Eo '[0-9].[0-9].[0-9]+')
          cat "$VAR-releasenotes"
          # ios_sdk_version=$(cat README.md | grep 'iOS AppsFlyerSDK \*\*v[0-9].[0-9].[0-9]\*\*')
          # android_sdk_version=$(cat README.md | grep 'Android AppsFlyerSDK \*\*v[0-9].[0-9].[0-9]\*\*')
          # fixed_version=$(echo "${{github.ref_name}}" | grep -Eo '[0-9].[0-9].[0-9]+')
          # jira_fixed_version="React-Native SDK v$fixed_version"
          # CHANGES=$(cat "$fixed_version-releasenotes".txt)
          # curl -X POST -H 'Content-type: application/json' --data '{"jira_fixed_version": "'"$jira_fixed_version"'", "deploy_type": "QA", "install_tag": "@QA", git_branch": "'"${{github.ref_name}}"'", "changes_and_fixes": "'"$CHANGES"'", "android_dependencie": "'"$android_sdk_version"'", "ios_dependencie": "'"$ios_sdk_version"'"}' "$SLACK_TOKEN"
